name: Release
on:
  push:
    branches: [ 'main' ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: release-please-demo
          bump-minor-pre-major: true
          version-file: "lib/alma_rest_client/version.rb"
      # Checkout code if release was created
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          ruby-version: 3.1
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: echo "this would be publish!"
